add singularity guide
NLESC-JCER/linux_actions_runner pull request #112
Opened 2020-07-06 17:30 UTC by fdiblen

2020-07-07 20:20 UTC, jspaaks requested changes
super job man

2020-07-07 21:13 UTC, sverhoeven requested changes
Trying it out with https://github.com/ci-for-research/example-python-1 repo with black check disabled in workflow. The jobs fails with incomplete job log and when I CTRL-C the singularity container, it errors with

```shell
---> Removing the runner.
Unhandled exception. System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.FlushInternalBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.FileStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Flush()
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.Write(String message)
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Trace(TraceEventType eventType, String message)
   at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile)
   at GitHub.Runner.Listener.Program.Main(String[] args)
./config.sh: line 79: 20881 Aborted                 (core dumped) ./bin/Runner.Listener "$@"
```

And keeps the runner (run.sh) running in the background. 

Is this because my tmpfs has 1.6Gb available?

2020-07-07 21:13 UTC, sverhoeven commented on ubuntu-singularity/README.md
> +In oder to use the Singularity image on a HPC cluster, we first need to create a jobscript. The job script will be handled by the scheduler and eventually it will set up the runner when it is execute
As you don't have root-permission on the HPC cluster you will need to build the github-actions-runner-singularity.sif file on your own machine and copy it to the cluster. Can a build+copy hint be added?

2020-07-08 07:55 UTC, jspaaks commented on .github/workflows/super-linter.yml
> +          VALIDATE_DOCKER: false
i fiddled with this extensively see https://github.com/ci-for-research/self-hosted-runners/pull/127

Summary:

- one of our Dockerfiles uses the word ``sudo``, to add a user to the sudo group. This seems to trigger the linter who thinks we are ``sudo`` doing something.
- disabling of rules is not very extensive in the linter, see https://github.com/github/super-linter/blob/master/docs/disabling-linters.md#dockerfile
-  I tried ``.dockerfilelintrc`` with ``rules: sudo_usage: off`` but that doesnt seem to be used correctly. Possibly due to https://github.com/github/super-linter/pull/384
- I tried the VALIDATE_DOCKER: false option, that disables linting on all files. Perhaps due to the counterintuitive way the defaults switch after adding one that see https://github.com/github/super-linter#environment-variables "_However if any one of the variables are set, we default to leaving any unset variable to false_"
- I made an issue to revisit this https://github.com/ci-for-research/self-hosted-runners/issues/128


Alternative approaches:
- avoid using sudo as a string in the Dockerfile, maybe using an env var or something.
- include all VALIDATE_[LANGUAGE] keys in the workflow file and setting them to true (excpet Docker)

Neither approach seems good, hence I decided to wait.

2020-07-08 08:50 UTC, fdiblen commented on ubuntu-singularity/README.md
> +
> 

This is also the reason why ``black-check`` action fails.

2020-10-02 13:16 UTC, fdiblen commented on ubuntu-singularity/github-actions-runner-singularity.def
>  From: ubuntu:19.10
changed to 20.04

2020-10-02 13:21 UTC, fdiblen commented on ubuntu-singularity/README.md
> +singularity instance start github-actions-runner-singularity.sif github-actions-runner --writable-tmpfs --bind ./env:/opt/actions-runner/.env
added the info.

2020-10-02 13:36 UTC, fdiblen commented on ubuntu-singularity/README.md
> +In oder to use the Singularity image on a HPC cluster, we first need to create a jobscript. The job script will be handled by the scheduler and eventually it will set up the runner when it is execute
added scp command

2020-10-02 13:39 UTC, fdiblen commented on .github/workflows/super-linter.yml
> +          VALIDATE_DOCKER: false
removed sudo command from the Docker file

2020-11-06 14:25 UTC, merged